const CardImages = {

    cards: {
        SPADESTWO: require("../assets/cards/SPADESTWO.png"),
        HEARTSTWO: require("../assets/cards/HEARTSTWO.png"),
        DIAMONDSTWO: require("../assets/cards/DIAMONDSTWO.png"),
        CLUBSTWO: require("../assets/cards/CLUBSTWO.png"),
        SPADESTHREE: require("../assets/cards/3_of_spades.png"),
        HEARTSTHREE: require("../assets/cards/3_of_hearts.png"),
        DIAMONDSTHREE: require("../assets/cards/3_of_diamonds.png"),
        CLUBSTHREE: require("../assets/cards/3_of_clubs.png"),
        SPADESFOUR: require("../assets/cards/4_of_spades.png"),
        HEARTSFOUR: require("../assets/cards/4_of_hearts.png"),
        DIAMONDSFOUR: require("../assets/cards/4_of_diamonds.png"),
        CLUBSFOUR: require("../assets/cards/4_of_clubs.png"),
        SPADESFIVE: require("../assets/cards/5_of_spades.png"),
        HEARTSFIVE: require("../assets/cards/5_of_hearts.png"),
        DIAMONDSFIVE: require("../assets/cards/5_of_diamonds.png"),
        CLUBSFIVE: require("../assets/cards/5_of_clubs.png"),
        SPADESSIX: require("../assets/cards/6_of_spades.png"),
        HEARTSSIX: require("../assets/cards/6_of_hearts.png"),
        DIAMONDSSIX: require("../assets/cards/6_of_diamonds.png"),
        CLUBSSIX: require("../assets/cards/6_of_clubs.png"),
        SPADESSEVEN: require("../assets/cards/7_of_spades.png"),
        HEARTSSEVEN: require("../assets/cards/7_of_hearts.png"),
        DIAMONDSSEVEN: require("../assets/cards/7_of_diamonds.png"),
        CLUBSSEVEN: require("../assets/cards/7_of_clubs.png"),
        SPADESEIGHT: require("../assets/cards/8_of_spades.png"),
        HEARTSEIGHT: require("../assets/cards/8_of_hearts.png"),
        DIAMONDSEIGHT: require("../assets/cards/8_of_diamonds.png"),
        CLUBSEIGHT: require("../assets/cards/8_of_clubs.png"),
        SPADESNINE: require("../assets/cards/9_of_spades.png"),
        HEARTSNINE: require("../assets/cards/9_of_hearts.png"),
        DIAMONDSNINE: require("../assets/cards/9_of_diamonds.png"),
        CLUBSNINE: require("../assets/cards/9_of_clubs.png"),
        SPADESTEN: require("../assets/cards/10_of_spades.png"),
        HEARTSTEN: require("../assets/cards/10_of_hearts.png"),
        DIAMONDSTEN: require("../assets/cards/10_of_diamonds.png"),
        CLUBSTEN: require("../assets/cards/10_of_clubs.png"),
        SPADESJACK: require("../assets/cards/jack_of_spades2.png"),
        HEARTSJACK: require("../assets/cards/jack_of_hearts2.png"),
        DIAMONDSJACK: require("../assets/cards/jack_of_diamonds2.png"),
        CLUBSJACK: require("../assets/cards/jack_of_clubs2.png"),
        SPADESQUEEN: require("../assets/cards/queen_of_spades2.png"),
        HEARTSQUEEN: require("../assets/cards/queen_of_hearts2.png"),
        DIAMONDSQUEEN: require("../assets/cards/queen_of_diamonds2.png"),
        CLUBSQUEEN: require("../assets/cards/queen_of_clubs2.png"),
        SPADESKING: require("../assets/cards/king_of_spades2.png"),
        HEARTSKING: require("../assets/cards/king_of_hearts2.png"),
        DIAMONDSKING: require("../assets/cards/king_of_diamonds2.png"),
        CLUBSKING: require("../assets/cards/king_of_clubs2.png"),
        SPADESACE: require("../assets/cards/ace_of_spades.png"),
        HEARTSACE: require("../assets/cards/ace_of_hearts.png"),
        DIAMONDSACE: require("../assets/cards/ace_of_diamonds.png"),
        CLUBSACE: require("../assets/cards/ace_of_clubs.png"),
    },

};

export default CardImages;
